# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    heatmap_repository:
        class: AppBundle\Repository\HeatmapRepository
    app.form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        arguments: ["@router", "@security.password_encoder"]
    user_data_set_repository:
        class: AppBundle\Repository\UserDataSetRepository
        arguments:
          - "@doctrine.orm.entity_manager"
    pro_data_set_repository:
        class: AppBundle\Repository\ProDataSetRepository
        arguments:
          - "@doctrine.orm.entity_manager"
    pro_repository:
        class: AppBundle\Repository\ProRepository
        arguments:
          - "@doctrine.orm.entity_manager"
